### ISSUE TITLE
What means ctx?

### ISSUE THREAD

**Issue by tmdghks9574** [ogay/hmac#2]
First, thank you for study SHA-512.
But, I don't know ctx mean... 
Please tell me ctx mean thank you

**Comment by langson6502** [comment]
Generally speaking, the term 'ctx' means 'context'. Context generally has to do with some kind of state that's necessary to perform an operation.

A sha256_ctx structure that contains all the information needed to calculate or reference the final digest.

**Comment by JackXammie** [comment]
What is AAX?
